# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "retry_policy Exponential {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 10000\n  }\n}\n\nclient<llm> GCPReasoner {\n  provider google-ai\n  retry_policy Exponential\n  options {\n    model \"gemini-3.1-pro-preview\"\n    api_key env.GCP_API_KEY\n  }\n}\n",
    "generators.baml": "// T1.1 — BAML codegen target for the bridge-side LLM router.\n//\n// `baml-cli generate --from src/dmac_assistant/router/baml_src` writes the\n// generated client into `<output_dir>/baml_client/`. We want the artifact at\n// `src/dmac_assistant/router/baml_client/`, which is a sibling of\n// `baml_src/`, so output_dir is \"../\" (relative to baml_src/).\n//\n// Version aligned with tools/e2e/baml_src/generators.baml so the bridge and\n// the e2e judge share the same baml_py runtime. Distinct from\n// vendor/chat_nextseek/.../baml_src/generators.baml (pins 0.221.0 for the\n// in-container Python 3.14 runtime).\n\ngenerator target {\n    output_type \"python/pydantic\"\n    output_dir \"../\"\n    version \"0.222.0\"\n    default_client_mode async\n}\n",
    "router.baml": "class TaskFamily {\n  name             string\n  description      string\n  example_queries  string[]\n}\n\nclass RouteCapability {\n  route_name     string\n  description    string\n  tools          string[]\n  best_for       string?\n  not_for        string?\n  task_families  TaskFamily[]\n}\n\nclass RouterInput {\n  user_query  string\n  routes      RouteCapability[]\n}\n\nenum Route {\n  NextseekQuery @alias(\"nextseek_query\")\n  ContainerCC   @alias(\"container_cc\")\n}\n\nenum ModelClass {\n  Sonnet @alias(\"sonnet\")\n  Haiku  @alias(\"haiku\")\n  Opus   @alias(\"opus\")\n}\n\nclass RouterDecision {\n  route        Route\n  model_class  ModelClass?\n  reasoning    string\n}\n\nfunction RouteQuery(input: RouterInput) -> RouterDecision {\n  client GCPReasoner\n  prompt #\"\n    You route a user query to one of the available execution routes for the\n    DMAC research assistant. Use the route's declared capabilities to decide.\n\n    {% for route in input.routes %}\n    ## {{ route.route_name }}\n    {{ route.description }}\n\n    Tools / plugins / skills: {{ route.tools|join(\", \") }}\n    {% if route.best_for %}Best for: {{ route.best_for }}{% endif %}\n    {% if route.not_for %}Avoid for: {{ route.not_for }}{% endif %}\n\n    Task families:\n    {% for tf in route.task_families %}\n    - {{ tf.name }} — {{ tf.description }}\n      Example queries:\n      {% for q in tf.example_queries %}\n      * \"{{ q }}\"\n      {% endfor %}\n    {% endfor %}\n    {% endfor %}\n\n    User query: {{ input.user_query }}\n\n    If you select `container_cc`, also pick a model class:\n      - haiku  : trivial Q&A / classification / short factual lookups\n      - sonnet : default general-purpose\n      - opus   : hard reasoning, multi-step planning, large refactors\n    If you select `nextseek_query`, omit model_class.\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map