# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def JudgeRouterAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RouterJudgeOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeRouterAnswer", llm_response=llm_response, mode="request")
        return typing.cast(types.RouterJudgeOutput, __result__)

    def JudgeUITranscript(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SimpleEvaluatorOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeUITranscript", llm_response=llm_response, mode="request")
        return typing.cast(types.SimpleEvaluatorOutput, __result__)

    def RouteQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RouterDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.RouterDecision, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def JudgeRouterAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RouterJudgeOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeRouterAnswer", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RouterJudgeOutput, __result__)

    def JudgeUITranscript(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SimpleEvaluatorOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeUITranscript", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SimpleEvaluatorOutput, __result__)

    def RouteQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RouterDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RouterDecision, __result__)

    