# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class RouteCapability(BaseModel):
    route_name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    tools: typing.List[str]
    best_for: typing.Optional[str] = None
    not_for: typing.Optional[str] = None
    task_families: typing.List["TaskFamily"]

class RouterDecision(BaseModel):
    route: typing.Optional[types.Route] = None
    model_class: typing.Optional[types.ModelClass] = None
    reasoning: typing.Optional[str] = None

class RouterInput(BaseModel):
    user_query: typing.Optional[str] = None
    routes: typing.List["RouteCapability"]

class RouterJudgeInput(BaseModel):
    query_id: typing.Optional[str] = None
    query_text: typing.Optional[str] = None
    expected_route: typing.Optional[str] = None
    actual_route: typing.Optional[str] = None
    reply_text: typing.Optional[str] = None
    frames_summary: typing.Optional[str] = None

class RouterJudgeOutput(BaseModel):
    verdict: typing.Optional[types.RouterJudgeVerdict] = None
    reasoning: typing.Optional[str] = None

class TaskFamily(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    example_queries: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
