# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class ModelClass(str, Enum):
    Sonnet = "Sonnet"
    Haiku = "Haiku"
    Opus = "Opus"

class Route(str, Enum):
    NextseekQuery = "NextseekQuery"
    ContainerCC = "ContainerCC"

# #########################################################################
# Generated classes (4)
# #########################################################################

class RouteCapability(BaseModel):
    route_name: str
    description: str
    tools: typing.List[str]
    best_for: typing.Optional[str] = None
    not_for: typing.Optional[str] = None
    task_families: typing.List["TaskFamily"]

class RouterDecision(BaseModel):
    route: Route
    model_class: typing.Optional[ModelClass] = None
    reasoning: str

class RouterInput(BaseModel):
    user_query: str
    routes: typing.List["RouteCapability"]

class TaskFamily(BaseModel):
    name: str
    description: str
    example_queries: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
