# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.RouteCapability": types.RouteCapability,
    "stream_types.RouteCapability": stream_types.RouteCapability,

    "types.RouterDecision": types.RouterDecision,
    "stream_types.RouterDecision": stream_types.RouterDecision,

    "types.RouterInput": types.RouterInput,
    "stream_types.RouterInput": stream_types.RouterInput,

    "types.TaskFamily": types.TaskFamily,
    "stream_types.TaskFamily": stream_types.TaskFamily,


    "types.ModelClass": types.ModelClass,

    "types.Route": types.Route,

}