# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (4)
# #########################################################################

class JudgeVerdict(str, Enum):
    Passed = "Passed"
    Failed = "Failed"
    Refused = "Refused"
    Unsupported = "Unsupported"
    Fabricated = "Fabricated"
    Error = "Error"

class ModelClass(str, Enum):
    Sonnet = "Sonnet"
    Haiku = "Haiku"
    Opus = "Opus"

class Route(str, Enum):
    NextseekQuery = "NextseekQuery"
    ContainerCC = "ContainerCC"

class RouterJudgeVerdict(str, Enum):
    Pass = "Pass"
    Fail = "Fail"
    Inconclusive = "Inconclusive"

# #########################################################################
# Generated classes (8)
# #########################################################################

class RouteCapability(BaseModel):
    route_name: str
    description: str
    tools: typing.List[str]
    best_for: typing.Optional[str] = None
    not_for: typing.Optional[str] = None
    task_families: typing.List["TaskFamily"]

class RouterDecision(BaseModel):
    route: Route
    model_class: typing.Optional[ModelClass] = None
    reasoning: str

class RouterInput(BaseModel):
    user_query: str
    routes: typing.List["RouteCapability"]

class RouterJudgeInput(BaseModel):
    query_id: str
    query_text: str
    expected_route: str
    actual_route: str
    reply_text: str
    frames_summary: str

class RouterJudgeOutput(BaseModel):
    verdict: RouterJudgeVerdict
    reasoning: str

class SimpleEvaluatorInput(BaseModel):
    query: str
    pass_criteria: str
    ui_answer: str

class SimpleEvaluatorOutput(BaseModel):
    verdict: JudgeVerdict
    reasoning: str
    model: str

class TaskFamily(BaseModel):
    name: str
    description: str
    example_queries: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
