"""Host-side orchestrator for the image-side binding coverage gate.

Plan B · T17a (Wave 6). Amendment 1 (2026-05-02 evening) close.

This test invokes pytest INSIDE dmac-assistant:poc with
  PYTHONPATH=/app/plugins/nextseek/bin
  --cov=_nextseek_runner (module-name form — file-path form silently
    produces 0% coverage; see §9.1 of task-B17a spec for rationale)
  --cov-fail-under=95
and asserts the docker run exits 0 (meaning: all tests pass AND
coverage >= 95%).

Credential source: host .env file (NEXTSEEK_USERNAME / NEXTSEEK_PASSWORD).
If absent, all tests in this module skip cleanly.

chat_nextseek host/image split: this file does NOT import chat_nextseek
and does NOT require pytest.importorskip — it only calls subprocess.run
(docker), which is available on the host.

Subprocess-based tests in this file (test_image_dry_run_dispatchers_emit_typed_json,
test_shim_tests_pass_in_image_without_chat_nextseek) are WIRING tests only —
they do not contribute to _nextseek_runner.py coverage measurement.
Coverage data is generated by tests/image/test_runner_coverage.py via
direct import in the same pytest process (see task-B17a §5.2).
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

from tests.harness.containers import IMAGE_TAG, docker_available

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_dotenv_creds() -> tuple[str, str] | None:
    """Return (API_USER, API_PASS) from .env, or None if absent/incomplete."""
    env_path = REPO_ROOT / ".env"
    if not env_path.is_file():
        return None
    try:
        from dotenv import dotenv_values  # type: ignore[import]
    except ImportError:
        # python-dotenv not installed on host; parse manually (stdlib fallback)
        creds: dict[str, str] = {}
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            creds[k.strip()] = v.strip().strip('"').strip("'")
    else:
        creds = dict(dotenv_values(env_path))

    username = creds.get("NEXTSEEK_USERNAME", "")
    password = creds.get("NEXTSEEK_PASSWORD", "")
    if not username or not password:
        return None
    return username, password


pytestmark = pytest.mark.skipif(
    not docker_available(),
    reason="docker daemon not available",
)


@pytest.fixture(scope="module")
def _image_creds() -> tuple[str, str]:
    """Skip this entire module if credentials are not in .env."""
    creds = _load_dotenv_creds()
    if creds is None:
        pytest.skip(
            "NEXTSEEK_USERNAME / NEXTSEEK_PASSWORD not found in .env — "
            "image binding gate skipped. Provide a .env file at repo root "
            "with real NExtSEEK dev credentials to run the gate."
        )
    return creds


def test_image_coverage_gate_passes(_image_creds: tuple[str, str]) -> None:
    """Amendment 1 close: image-side pytest with --cov-fail-under=95 exits 0.

    This is the BINDING >=95% gate deferred from Wave-3 Amendment 1
    (2026-05-02 evening). It is non-negotiable: if this test fails,
    B17a must NOT merge.

    Coverage is measured via direct-import tests in
    tests/image/test_runner_coverage.py. The pytest command uses
    PYTHONPATH=/app/plugins/nextseek/bin and --cov=_nextseek_runner
    (module-name form). File-path form (--cov=/app/...) silently yields
    0% data; module-name form with PYTHONPATH is empirically validated.

    Merge condition (verbatim from Amendment 1 forward-propagation rule):
      Image-side pytest suite green: all Wave-3 shim tests (test_shim_*.py)
      report PASSED (not skipped) inside the image. Full suite with
      --cov=build_context/plugins/nextseek/bin/_nextseek_runner.py
      --cov-fail-under=95 must report exit 0. This is the binding >=95%
      gate deferred from Wave-3 Amendment 1 (2026-05-02 evening) and is
      non-negotiable.
    """
    api_user, api_pass = _image_creds
    tests_image_dir = str(REPO_ROOT / "tests" / "image")

    cmd = [
        "docker", "run", "--rm",
        "-v", f"{tests_image_dir}:/host-tests/image:ro",
        "-e", f"API_USER={api_user}",
        "-e", f"API_PASS={api_pass}",
        "-e", "NEXTSEEK_DRY_RUN=1",
        "-e", "PYTHONPATH=/app/plugins/nextseek/bin",
        IMAGE_TAG,
        "python", "-m", "pytest",
        "/host-tests/image/test_runner_coverage.py",
        "--cov=_nextseek_runner",
        "--cov-fail-under=95",
        "--cov-report=term-missing",
        "-v",
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, (
        f"Image-side binding gate FAILED (exit={r.returncode}).\n"
        f"This means either a test failed OR coverage of "
        f"_nextseek_runner.py is below 95%.\n"
        f"--- stdout ---\n{r.stdout}\n"
        f"--- stderr ---\n{r.stderr}"
    )


def test_image_dry_run_dispatchers_emit_typed_json(_image_creds: tuple[str, str]) -> None:
    """Plan-body §B17.1: each agent dispatcher returns minimal valid JSON
    when NEXTSEEK_DRY_RUN=1, proving shim wiring without needing GCP / NExtSEEK.

    This is a WIRING test (subprocess-based). It does NOT contribute to
    _nextseek_runner.py coverage measurement. Coverage comes from
    tests/image/test_runner_coverage.py (direct-import architecture).
    """
    import json as _json

    api_user, api_pass = _image_creds
    cases = [
        ("nextseek-entity-extract", ["--query", "test"], "sampletypes"),
        (
            "nextseek-api-read",
            ["--parser-plan", '{"endpoint": "/x/", "method": "GET"}'],
            "endpoint",
        ),
        ("nextseek-plan", ["--query", "test"], "plan"),
    ]
    for shim, extra_args, expected_key in cases:
        cmd = [
            "docker", "run", "--rm",
            "-e", "NEXTSEEK_DRY_RUN=1",
            "-e", f"API_USER={api_user}",
            "-e", f"API_PASS={api_pass}",
            IMAGE_TAG,
            shim, *extra_args,
        ]
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        assert r.returncode == 0, (
            f"{shim} exit={r.returncode} stderr={r.stderr!r} stdout={r.stdout!r}"
        )
        try:
            payload = _json.loads(r.stdout)
        except _json.JSONDecodeError as exc:
            raise AssertionError(
                f"{shim} did not emit JSON on stdout: {exc}; stdout={r.stdout!r}"
            )
        assert expected_key in payload, (
            f"{shim} dry-run JSON missing key {expected_key!r}; got {payload!r}"
        )


def test_shim_tests_pass_in_image_without_chat_nextseek(
    _image_creds: tuple[str, str],
) -> None:
    """T11 (inverts the Wave-3 carryover): the 8 test_shim_*.py files must
    PASS inside the image with NO chat_nextseek installed — the thin dispatch
    path (shim -> _nextseek_runner.py -> sidecar/viewset client) runs without
    it. The old `skipped_count == 0`-means-chat_nextseek-present logic is
    gone: the importorskip gates were removed from the shim tests in T11
    step 6, so the files run unconditionally; the invariant is simply that
    they pass against an image that cannot import chat_nextseek (see
    test_image_smoke.py::test_chat_nextseek_absent_from_agent_image).

    This is a WIRING test (subprocess-based). It does NOT contribute to
    _nextseek_runner.py coverage measurement.

    Mount form: the entire repo root is mounted at /host-repo:ro so that
    REPO_ROOT = Path(__file__).resolve().parents[2] inside the container
    resolves to /host-repo (correct), and shim paths like
    /host-repo/build_context/plugins/nextseek/bin/nextseek-entity-extract
    exist via the bind-mount. Mounting only tests/unit/ would cause
    parents[2] to resolve to / and all shim paths would be /build_context/...
    which does not exist inside the image. See task-B17a §9.3 for the
    historical footnote explaining why /host-repo:ro is required.
    (Propagated from §9.3 per feedback_amendments_must_propagate_to_task_bodies.md)
    """
    api_user, api_pass = _image_creds
    # Mount the entire repo root so REPO_ROOT resolves correctly inside the container.
    repo_root_str = str(REPO_ROOT)

    cmd = [
        "docker", "run", "--rm",
        "-v", f"{repo_root_str}:/host-repo:ro",
        "-e", f"API_USER={api_user}",
        "-e", f"API_PASS={api_pass}",
        "-e", "NEXTSEEK_DRY_RUN=1",
        IMAGE_TAG,
        "python", "-m", "pytest",
        # Scope to the 8 shim files only. Collecting the whole tests/unit/ tree
        # also collects tests/unit/eval/*, whose module-level
        # pytest.importorskip("hibayes") skips at COLLECTION time (hibayes is
        # intentionally NOT in this image — the split-coverage model), which
        # would inflate the skipped count asserted below even though every shim
        # test passes. `-k test_shim` stays as a belt-and-suspenders filter.
        "/host-repo/tests/unit/test_shim_api_read.py",
        "/host-repo/tests/unit/test_shim_api_write.py",
        "/host-repo/tests/unit/test_shim_entity_extract.py",
        "/host-repo/tests/unit/test_shim_generate_submission.py",
        "/host-repo/tests/unit/test_shim_graph.py",
        "/host-repo/tests/unit/test_shim_parse.py",
        "/host-repo/tests/unit/test_shim_plan.py",
        "/host-repo/tests/unit/test_shim_report.py",
        "-k", "test_shim",
        "--no-cov",
        "-v",
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    output = r.stdout + r.stderr
    assert r.returncode == 0, (
        f"Shim tests inside image FAILED (exit={r.returncode}).\n"
        f"--- stdout ---\n{r.stdout}\n--- stderr ---\n{r.stderr}"
    )
    # Confirm at least some tests passed (guard against vacuous regex miss).
    passed_match = re.search(r"(\d+) passed", output)
    assert passed_match and int(passed_match.group(1)) > 0, (
        f"Shim tests inside image: could not confirm any items passed. "
        f"Either the pytest summary format changed or no tests ran. "
        f"output={output!r}"
    )
