"""Bridge-side copier: scratch/<user_id>/<rel> -> output/<user_id>/<rel>.

Runs after every container turn. Reads from the rw scratch volume on the
host, writes to the rw-on-host / ro-in-container output volume. CC never
touches the output dir directly. Symlinks and `..`/absolute relative
paths are refused (M2).

Plan A T12 — supersedes the T4 subdir-tree copier (Amendment 10).
"""
from __future__ import annotations

import logging
import re
import shutil
from pathlib import Path

log = logging.getLogger(__name__)

_USER_ID_RE = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")


def _is_safe_relpath(rel: str) -> bool:
    """Reject absolute paths and any path containing `..` segments.

    Lexical check is sufficient. Two-layer defense: paths produced by
    `run_tracker.snapshot_scratch_files` are generated by
    `Path.relative_to(user_dir)` and cannot contain `..` or be absolute.
    This guard defends only against external callers constructing
    adversarial `rel_paths` (e.g. a future caller that bypasses the
    snapshot). On POSIX, `..` and absolute components are the only
    lexical escape vectors for relative paths.
    """
    if not rel:
        return False
    p = Path(rel)
    if p.is_absolute():
        return False
    return ".." not in p.parts


def copy_files(
    scratch_root: Path,
    output_root: Path,
    user_id: str,
    rel_paths: set[str] | list[str],
) -> list[Path]:
    """Copy the listed relative paths from
    <scratch_root>/<user_id>/<rel> to <output_root>/<user_id>/<rel>.

    Returns destination paths actually written, sorted lexicographically.
    Skips: missing source, symlinks (M2), unsafe relative paths
    (absolute or containing `..`).
    """
    if not _USER_ID_RE.fullmatch(user_id):
        raise ValueError(f"invalid user_id: {user_id!r}")

    src_root = scratch_root / user_id
    dst_root = output_root / user_id
    written: list[Path] = []

    for rel in sorted(rel_paths):
        if not _is_safe_relpath(rel):
            log.warning("copier: refusing unsafe relpath %r", rel)
            continue
        src = src_root / rel
        if src.is_symlink():
            log.warning("copier: skipping symlink %s", src)
            continue
        if not src.is_file():
            # Vanished between snapshot and copy, or never existed. Skip.
            continue
        dst = dst_root / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        written.append(dst)
    return written
