"""Render README.md and container/CLAUDE.md block for NExtSEEK ingestion."""
from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable

from build_tools.ingest_nextseek_docs.constants import BEGIN_MARKER, END_MARKER
from build_tools.ingest_nextseek_docs.split import Section


def render_readme(
    sections: Iterable[Section],
    source_url: str,
    content_hash: str,
) -> str:
    """Render the full text of docs/nextseek/README.md."""
    lines = [
        "# NExtSEEK Documentation — Table of Contents",
        "",
        "_Generated by build_tools/ingest_nextseek_docs. Do not edit by hand._",
        "",
        f"Source: {source_url}",
        f"Content hash: {content_hash[:12]}",
        "",
        "## Sections",
        "",
    ]
    for section in sections:
        filename = f"{section.ordinal:02d}-{section.slug}.md"
        lines.append(f"- **[{section.title}]({filename})** — {section.description}")
    lines.append("")
    return "\n".join(lines)


def render_claude_md_block(
    sections: Iterable[Section],
    overview_paragraph: str,
) -> str:
    """Render the content that goes between BEGIN and END markers."""
    titles = ", ".join(section.title for section in sections)
    lines = [
        "",
        "## NExtSEEK Documentation",
        "",
        overview_paragraph,
        "",
        f"Top-level sections: {titles}.",
        "",
        "For detail, read `/app/docs/nextseek/README.md` first.",
    ]
    return "\n".join(lines) + "\n"


def update_claude_md(path: Path, block_content: str) -> None:
    """Atomically replace the marked block in path with block_content."""
    original = path.read_text()

    begin_count = original.count(BEGIN_MARKER)
    end_count = original.count(END_MARKER)
    if begin_count == 0 or end_count == 0:
        raise ValueError(
            f"missing marker in {path}: BEGIN count={begin_count}, "
            f"END count={end_count}. Expected exactly 1 of each."
        )
    if begin_count > 1 or end_count > 1:
        raise ValueError(
            f"duplicate marker in {path}: BEGIN count={begin_count}, "
            f"END count={end_count}. Expected exactly 1 of each."
        )

    begin_idx = original.index(BEGIN_MARKER)
    end_idx = original.index(END_MARKER)
    if begin_idx >= end_idx:
        raise ValueError(
            f"marker order inverted in {path}: BEGIN at {begin_idx}, END at {end_idx}"
        )

    prefix = original[: begin_idx + len(BEGIN_MARKER)]
    suffix = original[end_idx:]
    new_content = prefix + block_content + suffix

    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(new_content)
    try:
        os.replace(tmp, path)
    except OSError:
        if tmp.exists():
            tmp.unlink()
        raise
