"""Unit tests for build_tools.ingest_nextseek_docs.toc."""
from __future__ import annotations

from pathlib import Path

import pytest

from build_tools.ingest_nextseek_docs import toc
from build_tools.ingest_nextseek_docs.constants import BEGIN_MARKER, END_MARKER
from build_tools.ingest_nextseek_docs.split import Section


def _make_section(ordinal: int, title: str, slug: str, description: str) -> Section:
    return Section(
        ordinal=ordinal,
        title=title,
        slug=slug,
        body=f"# {title}\n\n{description}\n",
        description=description,
    )


SOURCE_URL = "https://koch-institute-mit.gitbook.io/mit-data-management-analysis-core/"
SAMPLE_SECTIONS = [
    _make_section(1, "Welcome", "welcome", "Intro paragraph for welcome."),
    _make_section(2, "Getting Started", "getting-started", "Short intro."),
]


def test_render_readme_golden_output() -> None:
    content_hash = "abc123def4567890deadbeefcafe0000abc123def4567890deadbeefcafe0000"
    result = toc.render_readme(SAMPLE_SECTIONS, SOURCE_URL, content_hash)
    expected = (
        "# NExtSEEK Documentation — Table of Contents\n"
        "\n"
        "_Generated by build_tools/ingest_nextseek_docs. Do not edit by hand._\n"
        "\n"
        f"Source: {SOURCE_URL}\n"
        f"Content hash: {content_hash[:12]}\n"
        "\n"
        "## Sections\n"
        "\n"
        "- **[Welcome](01-welcome.md)** — Intro paragraph for welcome.\n"
        "- **[Getting Started](02-getting-started.md)** — Short intro.\n"
    )
    assert result == expected


def test_render_claude_md_block_golden_output() -> None:
    sections = [
        _make_section(1, "Welcome", "welcome", "w"),
        _make_section(2, "Getting Started", "getting-started", "g"),
        _make_section(3, "Sample Registration", "sample-registration", "s"),
    ]
    overview = "NExtSEEK is the BMC sample tracking system."
    result = toc.render_claude_md_block(sections, overview)
    expected = (
        "\n"
        "## NExtSEEK Documentation\n"
        "\n"
        f"{overview}\n"
        "\n"
        "Top-level sections: Welcome, Getting Started, Sample Registration.\n"
        "\n"
        "For detail, read `/app/docs/nextseek/README.md` first.\n"
    )
    assert result == expected


def test_update_claude_md_replaces_block_between_markers(tmp_path: Path) -> None:
    seeded = (
        "# Header\n"
        f"{BEGIN_MARKER}\n"
        "OLD CONTENT\n"
        f"{END_MARKER}\n"
        "# Footer\n"
    )
    path = tmp_path / "CLAUDE.md"
    path.write_text(seeded)

    toc.update_claude_md(path, "\nNEW CONTENT\n")

    result = path.read_text()
    expected = (
        "# Header\n"
        f"{BEGIN_MARKER}\n"
        "NEW CONTENT\n"
        f"{END_MARKER}\n"
        "# Footer\n"
    )
    assert result == expected


def test_update_claude_md_begin_missing_raises(tmp_path: Path) -> None:
    original = f"Just content.\n{END_MARKER}\nFooter.\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(original)
    with pytest.raises(ValueError, match="marker"):
        toc.update_claude_md(path, "\nanything\n")
    assert path.read_text() == original


def test_update_claude_md_end_missing_raises(tmp_path: Path) -> None:
    original = f"Header\n{BEGIN_MARKER}\nJust content.\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(original)
    with pytest.raises(ValueError, match="marker"):
        toc.update_claude_md(path, "\nanything\n")
    assert path.read_text() == original


def test_update_claude_md_both_markers_missing_raises(tmp_path: Path) -> None:
    original = "# No markers here\nJust content.\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(original)
    with pytest.raises(ValueError, match="marker"):
        toc.update_claude_md(path, "\nanything\n")
    assert path.read_text() == original


def test_update_claude_md_begin_duplicated_raises(tmp_path: Path) -> None:
    doubled = f"{BEGIN_MARKER}\n1\n{END_MARKER}\n{BEGIN_MARKER}\n2\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(doubled)
    with pytest.raises(ValueError, match="marker"):
        toc.update_claude_md(path, "\nanything\n")
    assert path.read_text() == doubled


def test_update_claude_md_end_duplicated_raises(tmp_path: Path) -> None:
    doubled = f"{BEGIN_MARKER}\n1\n{END_MARKER}\n{END_MARKER}\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(doubled)
    with pytest.raises(ValueError, match="marker"):
        toc.update_claude_md(path, "\nanything\n")
    assert path.read_text() == doubled


def test_update_claude_md_inverted_marker_order_raises(tmp_path: Path) -> None:
    inverted = f"Prefix\n{END_MARKER}\nmiddle\n{BEGIN_MARKER}\nSuffix\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(inverted)
    with pytest.raises(ValueError, match="marker"):
        toc.update_claude_md(path, "\nanything\n")
    assert path.read_text() == inverted


def test_update_claude_md_is_atomic_on_replace_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original = f"{BEGIN_MARKER}\nold\n{END_MARKER}\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(original)

    def fake_replace(src, dst):
        raise OSError("disk full")

    monkeypatch.setattr(toc.os, "replace", fake_replace)
    with pytest.raises(OSError, match="disk full"):
        toc.update_claude_md(path, "\nnew\n")

    assert path.read_text() == original
    assert not (tmp_path / "CLAUDE.md.tmp").exists()


def test_update_claude_md_idempotent(tmp_path: Path) -> None:
    seeded = f"{BEGIN_MARKER}\n\n{END_MARKER}\n"
    path = tmp_path / "CLAUDE.md"
    path.write_text(seeded)

    block = "\nSAME CONTENT\n"
    toc.update_claude_md(path, block)
    first = path.read_bytes()
    toc.update_claude_md(path, block)
    second = path.read_bytes()
    assert first == second


def test_update_claude_md_uses_os_replace() -> None:
    import inspect

    src = inspect.getsource(toc.update_claude_md)
    assert "os.replace" in src
